name: Deploy
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 安装node
        uses: actions/setup-node@v3
        with:
          node-version: 22.19.0
      - name: 安装pnpm
        run: npm i pnpm@10.11.0 -g
      - name: 安装 npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc
      - name: 设置 pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: 安装依赖
        run: pnpm install
      - name: 打包
        run: pnpm build:all
      - name: 发包
        run: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: 同步 dist to docs/ (GitHub Pages source)
        run: |
          # 清空 docs 目录（GitHub Pages 源目录）
          rm -rf ./docs
          mkdir -p ./docs
          # 将构建产物复制到 docs/
          cp -r ./vitepress-docs/.vitepress/dist/* ./docs/

      - name: Commit and push changes
        run: |
          git config --local user.name [Github-Actions-Deploy]
          git config --local user.email zj-197@github.com
          git add -f ./docs
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping."
          else
            git commit -m "chore: deploy GitHub Pages"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          fi
      - name: 重新部署页面
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            })          
